// <auto-generated />
using System;
using Ch4Lab2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ch4Lab2.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20260126210009_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("Ch4Lab2.Models.Ancestry", b =>
                {
                    b.Property<int>("AncestryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AncestryId");

                    b.ToTable("Ancestors");

                    b.HasData(
                        new
                        {
                            AncestryId = 1,
                            Origin = "Elf"
                        },
                        new
                        {
                            AncestryId = 2,
                            Origin = "Dwarf"
                        },
                        new
                        {
                            AncestryId = 3,
                            Origin = "Halfling"
                        },
                        new
                        {
                            AncestryId = 4,
                            Origin = "Gnome"
                        },
                        new
                        {
                            AncestryId = 5,
                            Origin = "Human"
                        },
                        new
                        {
                            AncestryId = 6,
                            Origin = "Half-elf"
                        });
                });

            modelBuilder.Entity("Ch4Lab2.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AncestryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Intelligence")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Strength")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterID");

                    b.HasIndex("AncestryId");

                    b.HasIndex("ClassId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterID = 1,
                            AncestryId = 6,
                            ClassId = 5,
                            FirstName = "Markimus",
                            Intelligence = 11,
                            LastName = "Maximus",
                            Strength = 16
                        },
                        new
                        {
                            CharacterID = 2,
                            AncestryId = 2,
                            ClassId = 2,
                            FirstName = "Loismus",
                            Intelligence = 18,
                            LastName = "Blaismus",
                            Strength = 10
                        });
                });

            modelBuilder.Entity("Ch4Lab2.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            Name = "Bard"
                        },
                        new
                        {
                            ClassId = 2,
                            Name = "Cleric"
                        },
                        new
                        {
                            ClassId = 3,
                            Name = "Druid"
                        },
                        new
                        {
                            ClassId = 4,
                            Name = "Fighter"
                        },
                        new
                        {
                            ClassId = 5,
                            Name = "Paladin"
                        },
                        new
                        {
                            ClassId = 6,
                            Name = "Sorcerer"
                        });
                });

            modelBuilder.Entity("Ch4Lab2.Models.Character", b =>
                {
                    b.HasOne("Ch4Lab2.Models.Ancestry", "Ancestry")
                        .WithMany()
                        .HasForeignKey("AncestryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ch4Lab2.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ancestry");

                    b.Navigation("Class");
                });
#pragma warning restore 612, 618
        }
    }
}
